CREATE TABLE [dbo].[ACC_PARAMS] (
    [ACC_ID]     INT            NOT NULL,
    [PRM_ID]     INT            NOT NULL,
    [PRM_LONG]   INT            NULL,
    [PRM_STRING] NVARCHAR (255) NULL,
    [PRM_DOUBLE] FLOAT (53)     NULL,
    [PRM_DATE]   DATETIME       NULL,
    [PRM_CY]     MONEY          NULL,
    CONSTRAINT [PK_ACC_PARAMS] PRIMARY KEY NONCLUSTERED ([ACC_ID] ASC, [PRM_ID] ASC),
    CONSTRAINT [FK_ACC_PARAMS_ACC_PARAM_NAMES] FOREIGN KEY ([PRM_ID]) REFERENCES [dbo].[ACC_PARAM_NAMES] ([PRM_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_ACC_PARAMS_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[ACC_PARAMS] NOCHECK CONSTRAINT [FK_ACC_PARAMS_ACC_PARAM_NAMES];


GO
ALTER TABLE [dbo].[ACC_PARAMS] NOCHECK CONSTRAINT [FK_ACC_PARAMS_ACCOUNTS];


GO
GRANT DELETE
    ON OBJECT::[dbo].[ACC_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[ACC_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[ACC_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[ACC_PARAMS] TO [ap_public]
    AS [dbo];

