CREATE TABLE [dbo].[AG_BANKS] (
    [AB_PK]      INT            IDENTITY (1, 1) NOT NULL,
    [AG_ID]      INT            NOT NULL,
    [AB_NO]      INT            NOT NULL,
    [AB_MEMO]    NVARCHAR (255) NULL,
    [BANK_ID]    INT            NOT NULL,
    [AG_BANKACC] NVARCHAR (50)  NULL,
    [AB_TAG]     NVARCHAR (50)  NULL,
    [ACC_ID]     INT            NULL,
    [CRC_ID]     INT            NULL,
    [AB_FLAGS]   INT            NULL,
    CONSTRAINT [PK_AG_BANKS] PRIMARY KEY NONCLUSTERED ([AB_PK] ASC),
    CONSTRAINT [FK_AG_BANKS_ACCOUNTS] FOREIGN KEY ([ACC_ID]) REFERENCES [dbo].[ACCOUNTS] ([ACC_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_AG_BANKS_AGENTS] FOREIGN KEY ([AG_ID]) REFERENCES [dbo].[AGENTS] ([AG_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_AG_BANKS_BANKS] FOREIGN KEY ([BANK_ID]) REFERENCES [dbo].[BANKS] ([BANK_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_CURRENCIES_AG_BANKS] FOREIGN KEY ([CRC_ID]) REFERENCES [dbo].[CURRENCIES] ([CRC_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[AG_BANKS] NOCHECK CONSTRAINT [FK_AG_BANKS_ACCOUNTS];


GO
ALTER TABLE [dbo].[AG_BANKS] NOCHECK CONSTRAINT [FK_AG_BANKS_AGENTS];


GO
ALTER TABLE [dbo].[AG_BANKS] NOCHECK CONSTRAINT [FK_AG_BANKS_BANKS];


GO
CREATE NONCLUSTERED INDEX [IX_AG_BANKS_ACC_ID]
    ON [dbo].[AG_BANKS]([ACC_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_AG_BANKS_CRC_ID]
    ON [dbo].[AG_BANKS]([CRC_ID] ASC);

