CREATE TABLE [dbo].[AG_PARAMS] (
    [AG_ID]      INT            NOT NULL,
    [PRM_ID]     INT            NOT NULL,
    [PRM_LONG]   INT            NULL,
    [PRM_STRING] NVARCHAR (255) NULL,
    [PRM_DOUBLE] FLOAT (53)     NULL,
    [PRM_DATE]   DATETIME       NULL,
    [PRM_CY]     MONEY          NULL,
    CONSTRAINT [PK_AG_PARAMS] PRIMARY KEY NONCLUSTERED ([AG_ID] ASC, [PRM_ID] ASC),
    CONSTRAINT [FK_AG_PARAMS_AG_PARAM_NAMES] FOREIGN KEY ([PRM_ID]) REFERENCES [dbo].[AG_PARAM_NAMES] ([PRM_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_AG_PARAMS_AGENTS] FOREIGN KEY ([AG_ID]) REFERENCES [dbo].[AGENTS] ([AG_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[AG_PARAMS] NOCHECK CONSTRAINT [FK_AG_PARAMS_AG_PARAM_NAMES];


GO
ALTER TABLE [dbo].[AG_PARAMS] NOCHECK CONSTRAINT [FK_AG_PARAMS_AGENTS];


GO
GRANT DELETE
    ON OBJECT::[dbo].[AG_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[AG_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[AG_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[AG_PARAMS] TO [ap_public]
    AS [dbo];

