CREATE TABLE [dbo].[BIND_DOCS] (
    [PK]      INT IDENTITY (1, 1) NOT NULL,
    [BIND_ID] INT NOT NULL,
    [DOC_ID]  INT NULL,
    [BIND_NO] INT NULL,
    CONSTRAINT [PK_BIND_DOCS] PRIMARY KEY NONCLUSTERED ([PK] ASC),
    CONSTRAINT [FK_BIND_DOCS_BINDERS] FOREIGN KEY ([BIND_ID]) REFERENCES [dbo].[BINDERS] ([BIND_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_BIND_DOCS_DOCUMENTS] FOREIGN KEY ([DOC_ID]) REFERENCES [dbo].[DOCUMENTS] ([DOC_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[BIND_DOCS] NOCHECK CONSTRAINT [FK_BIND_DOCS_BINDERS];


GO
ALTER TABLE [dbo].[BIND_DOCS] NOCHECK CONSTRAINT [FK_BIND_DOCS_DOCUMENTS];


GO
GRANT SELECT
    ON OBJECT::[dbo].[BIND_DOCS] TO [ap_public]
    AS [dbo];

