CREATE TABLE [dbo].[BIND_PARAMS] (
    [BIND_ID]    INT            NOT NULL,
    [PRM_ID]     INT            NOT NULL,
    [PRM_LONG]   INT            NULL,
    [PRM_STRING] NVARCHAR (255) NULL,
    [PRM_DOUBLE] FLOAT (53)     NULL,
    [PRM_DATE]   DATETIME       NULL,
    [PRM_CY]     MONEY          NULL,
    CONSTRAINT [PK_BIND_PARAMS] PRIMARY KEY NONCLUSTERED ([BIND_ID] ASC, [PRM_ID] ASC),
    CONSTRAINT [FK_BIND_PARAMS_BIND_PARAM_NAMES] FOREIGN KEY ([PRM_ID]) REFERENCES [dbo].[BIND_PARAM_NAMES] ([PRM_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_BIND_PARAMS_BINDERS] FOREIGN KEY ([BIND_ID]) REFERENCES [dbo].[BINDERS] ([BIND_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[BIND_PARAMS] NOCHECK CONSTRAINT [FK_BIND_PARAMS_BIND_PARAM_NAMES];


GO
ALTER TABLE [dbo].[BIND_PARAMS] NOCHECK CONSTRAINT [FK_BIND_PARAMS_BINDERS];


GO
GRANT DELETE
    ON OBJECT::[dbo].[BIND_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[BIND_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[BIND_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[BIND_PARAMS] TO [ap_public]
    AS [dbo];

