CREATE TABLE [dbo].[CRC_RATES] (
    [PK]      INT      IDENTITY (1, 1) NOT NULL,
    [CRC_ID]  INT      NOT NULL,
    [RT_ID]   INT      NOT NULL,
    [RT_DATE] DATETIME NULL,
    [RT_NUM]  MONEY    NULL,
    CONSTRAINT [PK_CRC_RATES] PRIMARY KEY NONCLUSTERED ([PK] ASC),
    CONSTRAINT [FK_CRC_RATES_CRC_RT_NAMES] FOREIGN KEY ([RT_ID]) REFERENCES [dbo].[CRC_RT_NAMES] ([RT_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_CRC_RATES_CURRENCIES] FOREIGN KEY ([CRC_ID]) REFERENCES [dbo].[CURRENCIES] ([CRC_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[CRC_RATES] NOCHECK CONSTRAINT [FK_CRC_RATES_CRC_RT_NAMES];


GO
ALTER TABLE [dbo].[CRC_RATES] NOCHECK CONSTRAINT [FK_CRC_RATES_CURRENCIES];

