CREATE TABLE [dbo].[DOC_FACTS] (
    [EL_ID]     INT            NOT NULL,
    [FA_ID]     INT            NOT NULL,
    [FA_FDATE]  DATETIME       NOT NULL,
    [FA_LONG]   INT            NULL,
    [FA_STRING] NVARCHAR (255) NULL,
    [FA_DOUBLE] FLOAT (53)     NULL,
    [FA_DATE]   DATETIME       NULL,
    [FA_CY]     MONEY          NULL,
    CONSTRAINT [PK_DOC_FACTS] PRIMARY KEY NONCLUSTERED ([EL_ID] ASC, [FA_ID] ASC, [FA_FDATE] ASC),
    CONSTRAINT [FK_DOC_FACTS_DOC_FACT_NAMES] FOREIGN KEY ([FA_ID]) REFERENCES [dbo].[DOC_FACT_NAMES] ([FA_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_DOC_FACTS_DOCUMENTS] FOREIGN KEY ([EL_ID]) REFERENCES [dbo].[DOCUMENTS] ([DOC_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[DOC_FACTS] NOCHECK CONSTRAINT [FK_DOC_FACTS_DOC_FACT_NAMES];


GO
ALTER TABLE [dbo].[DOC_FACTS] NOCHECK CONSTRAINT [FK_DOC_FACTS_DOCUMENTS];

