CREATE TABLE [dbo].[DOCUMENTS] (
    [DOC_ID]      INT              IDENTITY (1, 1) NOT NULL,
    [DOC_GUID]    UNIQUEIDENTIFIER CONSTRAINT [DF_DOCUMENTS_DOC_GUID] DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    [DOC_DATE]    DATETIME         NOT NULL,
    [DOC_DONE]    SMALLINT         NOT NULL,
    [DOC_NO]      NVARCHAR (32)    NULL,
    [DOC_SUM]     MONEY            NULL,
    [TML_ID]      INT              NULL,
    [FRM_ID]      INT              NULL,
    [FLD_ID]      INT              NULL,
    [MC_ID]       INT              NULL,
    [DOC_NAME]    NVARCHAR (255)   NULL,
    [DOC_TAG]     NVARCHAR (50)    NULL,
    [DOC_MEMO]    NVARCHAR (255)   NULL,
    [DOC_SUM_CRC] MONEY            NULL,
    [DOC_PS1]     NVARCHAR (50)    NULL,
    [DOC_PS2]     NVARCHAR (50)    NULL,
    [DOC_PS3]     NVARCHAR (50)    NULL,
    [DOC_PC1]     MONEY            NULL,
    [DOC_PC2]     MONEY            NULL,
    [DOC_PC3]     MONEY            NULL,
    [DOC_PD1]     DATETIME         NULL,
    [DOC_PD2]     DATETIME         NULL,
    [DOC_PD3]     DATETIME         NULL,
    [DOC_PL1]     INT              NULL,
    [DOC_PL2]     INT              NULL,
    [DOC_PL3]     INT              NULL,
    [DOC_LINK]    INT              NULL,
    [ST_ID]       INT              NULL,
    [LAST_DATE]   DATETIME         NULL,
    [UID]         NVARCHAR (50)    NULL,
    [DOC_EXTEXT]  NTEXT            NULL,
    [DOC_XSTATUS] NCHAR (3)        NULL,
    CONSTRAINT [PK_DOCUMENTS] PRIMARY KEY NONCLUSTERED ([DOC_ID] ASC),
    CONSTRAINT [FK_AGENTS_DOCUMENTS_MC] FOREIGN KEY ([MC_ID]) REFERENCES [dbo].[AGENTS] ([AG_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_DOCUMENTS_DOCUMENTS] FOREIGN KEY ([DOC_LINK]) REFERENCES [dbo].[DOCUMENTS] ([DOC_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_DOCUMENTS_FOLDERS] FOREIGN KEY ([FLD_ID]) REFERENCES [dbo].[FOLDERS] ([FLD_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_DOCUMENTS_FORMS] FOREIGN KEY ([FRM_ID]) REFERENCES [dbo].[FORMS] ([FRM_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_DOCUMENTS_STATES] FOREIGN KEY ([ST_ID]) REFERENCES [dbo].[STATES] ([ST_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_DOCUMENTS_TEMPLATES] FOREIGN KEY ([TML_ID]) REFERENCES [dbo].[TEMPLATES] ([TML_ID]) NOT FOR REPLICATION,
    CONSTRAINT [IX_DOCUMENTS_GUID] UNIQUE NONCLUSTERED ([DOC_GUID] ASC)
);


GO
ALTER TABLE [dbo].[DOCUMENTS] NOCHECK CONSTRAINT [FK_DOCUMENTS_DOCUMENTS];


GO
ALTER TABLE [dbo].[DOCUMENTS] NOCHECK CONSTRAINT [FK_DOCUMENTS_FOLDERS];


GO
ALTER TABLE [dbo].[DOCUMENTS] NOCHECK CONSTRAINT [FK_DOCUMENTS_FORMS];


GO
ALTER TABLE [dbo].[DOCUMENTS] NOCHECK CONSTRAINT [FK_DOCUMENTS_STATES];


GO
ALTER TABLE [dbo].[DOCUMENTS] NOCHECK CONSTRAINT [FK_DOCUMENTS_TEMPLATES];


GO
CREATE CLUSTERED INDEX [IX_DOCUMENTS_DATE2]
    ON [dbo].[DOCUMENTS]([DOC_DATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DOCUMENTS_DOC_LINK]
    ON [dbo].[DOCUMENTS]([DOC_LINK] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DOCUMENTS_MC_ID]
    ON [dbo].[DOCUMENTS]([MC_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DOCUMENTS_TML]
    ON [dbo].[DOCUMENTS]([TML_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DOCUMENTS_ST_ID]
    ON [dbo].[DOCUMENTS]([ST_ID] ASC);


GO
--------------------------------------
create trigger documents_Dtrig on DOCUMENTS
for delete as

-- cascade deletes from JOURNAL
delete JOURNAL from deleted inner join JOURNAL ON deleted.DOC_ID = JOURNAL.DOC_ID
-- cascade deletes from DOC_PARAMS
delete DOC_PARAMS from deleted inner join DOC_PARAMS ON deleted.DOC_ID = DOC_PARAMS.DOC_ID
-- update DOC_LINK
update DOCUMENTS set DOC_LINK=null where DOC_LINK in (select deleted.DOC_ID from deleted)
-- clear JOURNAL.PDOC_ID
update JOURNAL set PDOC_ID=NULL where PDOC_ID in (select deleted.DOC_ID from deleted)
-- cascade deletes from BIND_DOCS
delete BIND_DOCS from deleted inner join BIND_DOCS ON deleted.DOC_ID = BIND_DOCS.DOC_ID
-- cascade deletes from DOC_FACTS
delete DOC_FACTS from deleted inner join DOC_FACTS ON deleted.DOC_ID = DOC_FACTS.EL_ID


GO
GRANT SELECT
    ON OBJECT::[dbo].[DOCUMENTS] TO [ap_public]
    AS [dbo];

