CREATE TABLE [dbo].[ENT_UNITS] (
    [EU_PK]    INT   IDENTITY (1, 1) NOT NULL,
    [ENT_ID]   INT   NOT NULL,
    [UN_ID]    INT   NOT NULL,
    [EU_NO]    INT   NOT NULL,
    [EU_NUM]   MONEY NOT NULL,
    [EU_DENOM] MONEY NOT NULL,
    CONSTRAINT [PK_ENT_UNITS] PRIMARY KEY CLUSTERED ([EU_PK] ASC),
    CONSTRAINT [FK_ENT_UNITS_ENTITIES] FOREIGN KEY ([ENT_ID]) REFERENCES [dbo].[ENTITIES] ([ENT_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_ENT_UNITS_UNITS] FOREIGN KEY ([UN_ID]) REFERENCES [dbo].[UNITS] ([UN_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[ENT_UNITS] NOCHECK CONSTRAINT [FK_ENT_UNITS_ENTITIES];


GO
ALTER TABLE [dbo].[ENT_UNITS] NOCHECK CONSTRAINT [FK_ENT_UNITS_UNITS];


GO
CREATE NONCLUSTERED INDEX [IX_ENT_UNITS_ENT_ID]
    ON [dbo].[ENT_UNITS]([ENT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_ENT_UNITS_UN_ID]
    ON [dbo].[ENT_UNITS]([UN_ID] ASC);

