CREATE TABLE [dbo].[ENUMS] (
    [ENM_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [ENN_ID]   INT           NOT NULL,
    [ENM_NAME] NVARCHAR (50) NOT NULL,
    [ENM_TAG]  NVARCHAR (50) NULL,
    CONSTRAINT [PK_ENUMS] PRIMARY KEY CLUSTERED ([ENM_ID] ASC),
    CONSTRAINT [FK_ENUMS_ENUM_NAMES] FOREIGN KEY ([ENN_ID]) REFERENCES [dbo].[ENUM_NAMES] ([ENN_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[ENUMS] NOCHECK CONSTRAINT [FK_ENUMS_ENUM_NAMES];


GO
CREATE NONCLUSTERED INDEX [IX_ENUMS_ENNID]
    ON [dbo].[ENUMS]([ENN_ID] ASC);

