CREATE TABLE [dbo].[FLD_PARAMS] (
    [FLD_ID]     INT            NOT NULL,
    [PRM_ID]     INT            NOT NULL,
    [PRM_LONG]   INT            NULL,
    [PRM_STRING] NVARCHAR (255) NULL,
    [PRM_DOUBLE] FLOAT (53)     NULL,
    [PRM_DATE]   DATETIME       NULL,
    [PRM_CY]     MONEY          NULL,
    CONSTRAINT [PK_FLD_PARAMS] PRIMARY KEY NONCLUSTERED ([FLD_ID] ASC, [PRM_ID] ASC),
    CONSTRAINT [FK_FLD_PARAMS_FLD_PARAM_NAMES] FOREIGN KEY ([PRM_ID]) REFERENCES [dbo].[FLD_PARAM_NAMES] ([PRM_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_FLD_PARAMS_FOLDERS] FOREIGN KEY ([FLD_ID]) REFERENCES [dbo].[FOLDERS] ([FLD_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[FLD_PARAMS] NOCHECK CONSTRAINT [FK_FLD_PARAMS_FLD_PARAM_NAMES];


GO
ALTER TABLE [dbo].[FLD_PARAMS] NOCHECK CONSTRAINT [FK_FLD_PARAMS_FOLDERS];


GO
GRANT DELETE
    ON OBJECT::[dbo].[FLD_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[FLD_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[FLD_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[FLD_PARAMS] TO [ap_public]
    AS [dbo];

