CREATE TABLE [dbo].[FRM_AUTONUM] (
    [FA_ID]      INT           IDENTITY (1, 1) NOT NULL,
    [FA_NAME]    NVARCHAR (50) NULL,
    [AN_PREFIX]  NVARCHAR (50) NULL,
    [AN_SUFFIX]  NVARCHAR (50) NULL,
    [AN_CURRENT] INT           NOT NULL,
    CONSTRAINT [PK_FRM_AUTONUM] PRIMARY KEY NONCLUSTERED ([FA_ID] ASC)
);

