CREATE TABLE [dbo].[FRM_PARAMS] (
    [FRM_ID]     INT            NOT NULL,
    [PRM_ID]     INT            NOT NULL,
    [PRM_LONG]   INT            NULL,
    [PRM_STRING] NVARCHAR (255) NULL,
    [PRM_DOUBLE] FLOAT (53)     NULL,
    [PRM_DATE]   DATETIME       NULL,
    [PRM_CY]     MONEY          NULL,
    CONSTRAINT [PK_FRM_PARAMS] PRIMARY KEY NONCLUSTERED ([FRM_ID] ASC, [PRM_ID] ASC),
    CONSTRAINT [FK_FRM_PARAMS_FORMS] FOREIGN KEY ([FRM_ID]) REFERENCES [dbo].[FORMS] ([FRM_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_FRM_PARAMS_FRM_PARAM_NAMES] FOREIGN KEY ([PRM_ID]) REFERENCES [dbo].[FRM_PARAM_NAMES] ([PRM_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[FRM_PARAMS] NOCHECK CONSTRAINT [FK_FRM_PARAMS_FORMS];


GO
ALTER TABLE [dbo].[FRM_PARAMS] NOCHECK CONSTRAINT [FK_FRM_PARAMS_FRM_PARAM_NAMES];


GO
GRANT DELETE
    ON OBJECT::[dbo].[FRM_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[FRM_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[FRM_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[FRM_PARAMS] TO [ap_public]
    AS [dbo];

