CREATE TABLE [dbo].[JRN_PARAMS] (
    [J_ID]       INT            NOT NULL,
    [PRM_ID]     INT            NOT NULL,
    [PRM_LONG]   INT            NULL,
    [PRM_STRING] NVARCHAR (255) NULL,
    [PRM_DOUBLE] FLOAT (53)     NULL,
    [PRM_DATE]   DATETIME       NULL,
    [PRM_CY]     MONEY          NULL,
    CONSTRAINT [PK_JRN_PARAMS] PRIMARY KEY NONCLUSTERED ([J_ID] ASC, [PRM_ID] ASC),
    CONSTRAINT [FK_JRN_PARAMS_JOURNAL] FOREIGN KEY ([J_ID]) REFERENCES [dbo].[JOURNAL] ([J_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_JRN_PARAMS_JRN_PARAM_NAMES] FOREIGN KEY ([PRM_ID]) REFERENCES [dbo].[JRN_PARAM_NAMES] ([PRM_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[JRN_PARAMS] NOCHECK CONSTRAINT [FK_JRN_PARAMS_JOURNAL];


GO
ALTER TABLE [dbo].[JRN_PARAMS] NOCHECK CONSTRAINT [FK_JRN_PARAMS_JRN_PARAM_NAMES];


GO
GRANT DELETE
    ON OBJECT::[dbo].[JRN_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[JRN_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[JRN_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[JRN_PARAMS] TO [ap_public]
    AS [dbo];

