CREATE TABLE [dbo].[JRN_CRC] (
    [JC_KEY]   INT   IDENTITY (1, 1) NOT NULL,
    [J_ID]     INT   NOT NULL,
    [CRC_ID]   INT   NOT NULL,
    [JC_NO]    INT   NOT NULL,
    [JC_SUM]   MONEY CONSTRAINT [JRN_CRC_DEF_JC_SUM] DEFAULT ((0)) NOT NULL,
    [RT_ID]    INT   NULL,
    [JC_PRICE] MONEY NULL,
    [JC_RATE]  MONEY NULL,
    CONSTRAINT [PK_JRN_CRC] PRIMARY KEY NONCLUSTERED ([JC_KEY] ASC),
    CONSTRAINT [FK_JRN_CRC_CURRENCIES] FOREIGN KEY ([CRC_ID]) REFERENCES [dbo].[CURRENCIES] ([CRC_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_JRN_CRC_JOURNAL] FOREIGN KEY ([J_ID]) REFERENCES [dbo].[JOURNAL] ([J_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[JRN_CRC] NOCHECK CONSTRAINT [FK_JRN_CRC_CURRENCIES];


GO
ALTER TABLE [dbo].[JRN_CRC] NOCHECK CONSTRAINT [FK_JRN_CRC_JOURNAL];


GO
CREATE NONCLUSTERED INDEX [IX_JRN_CRC_CRC_ID]
    ON [dbo].[JRN_CRC]([CRC_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_JRN_CRC_J_ID]
    ON [dbo].[JRN_CRC]([J_ID] ASC);


GO
GRANT SELECT
    ON OBJECT::[dbo].[JRN_CRC] TO [ap_public]
    AS [dbo];

