CREATE TABLE [dbo].[MENU_ACTIONS] (
    [PK]       INT           IDENTITY (1, 1) NOT NULL,
    [MA_NO]    INT           NULL,
    [MA_NAME]  NVARCHAR (50) NULL,
    [MA_FILE]  NVARCHAR (50) NULL,
    [MA_LEVEL] INT           NULL,
    CONSTRAINT [PK_MENU_ACTIONS] PRIMARY KEY CLUSTERED ([PK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_MENU_ACTIONS_MA_NO]
    ON [dbo].[MENU_ACTIONS]([MA_NO] ASC);

