CREATE TABLE [dbo].[MISC_PARAMS] (
    [MSC_ID]     INT            NOT NULL,
    [PRM_ID]     INT            NOT NULL,
    [PRM_LONG]   INT            NULL,
    [PRM_STRING] NVARCHAR (255) NULL,
    [PRM_DOUBLE] FLOAT (53)     NULL,
    [PRM_DATE]   DATETIME       NULL,
    [PRM_CY]     MONEY          NULL,
    CONSTRAINT [PK_MISC_PARAMS] PRIMARY KEY NONCLUSTERED ([MSC_ID] ASC, [PRM_ID] ASC),
    CONSTRAINT [FK_MISC_PARAMS_MISC] FOREIGN KEY ([MSC_ID]) REFERENCES [dbo].[MISC] ([MSC_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_MISC_PARAMS_MISC_PARAM_NAMES] FOREIGN KEY ([PRM_ID]) REFERENCES [dbo].[MISC_PARAM_NAMES] ([PRM_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[MISC_PARAMS] NOCHECK CONSTRAINT [FK_MISC_PARAMS_MISC];


GO
ALTER TABLE [dbo].[MISC_PARAMS] NOCHECK CONSTRAINT [FK_MISC_PARAMS_MISC_PARAM_NAMES];


GO
GRANT DELETE
    ON OBJECT::[dbo].[MISC_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[MISC_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[MISC_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[MISC_PARAMS] TO [ap_public]
    AS [dbo];

