CREATE TABLE [dbo].[NORMS] (
    [NRM_ID]    INT            IDENTITY (1, 1) NOT NULL,
    [NRM_NAME]  NVARCHAR (255) NOT NULL,
    [NRM_XNAME] NVARCHAR (50)  NOT NULL,
    [NRM_YNAME] NVARCHAR (50)  NOT NULL,
    [NRM_CODE]  NVARCHAR (50)  NOT NULL,
    [NRM_MEMO]  NVARCHAR (255) NULL,
    CONSTRAINT [PK_NORMS] PRIMARY KEY CLUSTERED ([NRM_ID] ASC)
);

