CREATE TABLE [dbo].[NORM_VALUES] (
    [NRM_ID]  INT        NOT NULL,
    [NRM_X]   INT        NOT NULL,
    [NRM_Y]   INT        NOT NULL,
    [NRM_DBL] FLOAT (53) NULL,
    CONSTRAINT [PK_NORM_VALUES] PRIMARY KEY CLUSTERED ([NRM_ID] ASC, [NRM_X] ASC, [NRM_Y] ASC),
    CONSTRAINT [FK_NORM_VALUES_NORMS] FOREIGN KEY ([NRM_ID]) REFERENCES [dbo].[NORMS] ([NRM_ID]) ON DELETE CASCADE NOT FOR REPLICATION
);

