CREATE TABLE [dbo].[PRC_CONTENTS] (
    [PK]        INT      IDENTITY (1, 1) NOT NULL,
    [PRC_DATE]  DATETIME NOT NULL,
    [ENT_ID]    INT      NOT NULL,
    [PRC_ID]    INT      NOT NULL,
    [PRL_ID]    INT      NULL,
    [PRC_VALUE] MONEY    NULL,
    CONSTRAINT [PK_PRC_CONTENTS] PRIMARY KEY NONCLUSTERED ([PK] ASC),
    CONSTRAINT [FK_PRC_CONTENTS_ENTITIES] FOREIGN KEY ([ENT_ID]) REFERENCES [dbo].[ENTITIES] ([ENT_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_PRC_CONTENTS_PRC_NAMES] FOREIGN KEY ([PRC_ID]) REFERENCES [dbo].[PRC_NAMES] ([PRC_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[PRC_CONTENTS] NOCHECK CONSTRAINT [FK_PRC_CONTENTS_ENTITIES];


GO
ALTER TABLE [dbo].[PRC_CONTENTS] NOCHECK CONSTRAINT [FK_PRC_CONTENTS_PRC_NAMES];


GO
CREATE NONCLUSTERED INDEX [IX_PRC_CONTENTS_ENT_ID]
    ON [dbo].[PRC_CONTENTS]([ENT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PRC_CONTENTS_PRL_ID]
    ON [dbo].[PRC_CONTENTS]([PRL_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_PRC_CONTENTS_PRC_ID]
    ON [dbo].[PRC_CONTENTS]([PRC_ID] ASC);

