CREATE TABLE [dbo].[PRL_PRICES] (
    [PRLPC]  INT IDENTITY (1, 1) NOT NULL,
    [PRL_ID] INT NOT NULL,
    [PRC_ID] INT NOT NULL,
    [PRC_NO] INT NOT NULL,
    CONSTRAINT [PK_PRL_PRICES] PRIMARY KEY NONCLUSTERED ([PRLPC] ASC),
    CONSTRAINT [FK_PRL_PRICES_PRC_NAMES] FOREIGN KEY ([PRC_ID]) REFERENCES [dbo].[PRC_NAMES] ([PRC_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_PRL_PRICES_PRL_LISTS] FOREIGN KEY ([PRL_ID]) REFERENCES [dbo].[PRL_LISTS] ([PRL_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[PRL_PRICES] NOCHECK CONSTRAINT [FK_PRL_PRICES_PRC_NAMES];


GO
ALTER TABLE [dbo].[PRL_PRICES] NOCHECK CONSTRAINT [FK_PRL_PRICES_PRL_LISTS];

