CREATE TABLE [dbo].[RCP_PARAMS] (
    [RP_ID]      INT            NOT NULL,
    [PRM_ID]     INT            NOT NULL,
    [PRM_LONG]   INT            NULL,
    [PRM_STRING] NVARCHAR (255) NULL,
    [PRM_DOUBLE] FLOAT (53)     NULL,
    [PRM_DATE]   DATETIME       NULL,
    [PRM_CY]     MONEY          NULL,
    CONSTRAINT [PK_RCP_PARAMS] PRIMARY KEY NONCLUSTERED ([RP_ID] ASC, [PRM_ID] ASC),
    CONSTRAINT [FK_RCP_PARAMS_RCP_PARAM_NAMES] FOREIGN KEY ([PRM_ID]) REFERENCES [dbo].[RCP_PARAM_NAMES] ([PRM_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_RCP_PARAMS_RECIPES] FOREIGN KEY ([RP_ID]) REFERENCES [dbo].[RECIPES] ([RP_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[RCP_PARAMS] NOCHECK CONSTRAINT [FK_RCP_PARAMS_RCP_PARAM_NAMES];


GO
ALTER TABLE [dbo].[RCP_PARAMS] NOCHECK CONSTRAINT [FK_RCP_PARAMS_RECIPES];

