CREATE TABLE [dbo].[RIGHTS] (
    [PK]     INT           IDENTITY (1, 1) NOT NULL,
    [UID]    NVARCHAR (50) NULL,
    [KIND]   SMALLINT      NULL,
    [KINDID] INT           NULL,
    [FLAGS]  INT           NULL,
    CONSTRAINT [PK_RIGHTS] PRIMARY KEY CLUSTERED ([PK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_RIGHTS_UID]
    ON [dbo].[RIGHTS]([UID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_RIGHTS_KIND]
    ON [dbo].[RIGHTS]([KIND] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_RIGHTS_KINDID]
    ON [dbo].[RIGHTS]([KINDID] ASC);

