CREATE TABLE [dbo].[RPE_PARAMS] (
    [RC_ID]      INT            NOT NULL,
    [PRM_ID]     INT            NOT NULL,
    [PRM_LONG]   INT            NULL,
    [PRM_STRING] NVARCHAR (255) NULL,
    [PRM_DOUBLE] FLOAT (53)     NULL,
    [PRM_DATE]   DATETIME       NULL,
    [PRM_CY]     MONEY          NULL,
    CONSTRAINT [PK_RPE_PARAMS] PRIMARY KEY NONCLUSTERED ([RC_ID] ASC, [PRM_ID] ASC),
    CONSTRAINT [FK_RPE_PARAMS_RP_CONTENTS] FOREIGN KEY ([RC_ID]) REFERENCES [dbo].[RP_CONTENTS] ([RC_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_RPE_PARAMS_RPE_PARAM_NAMES] FOREIGN KEY ([PRM_ID]) REFERENCES [dbo].[RPE_PARAM_NAMES] ([PRM_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[RPE_PARAMS] NOCHECK CONSTRAINT [FK_RPE_PARAMS_RP_CONTENTS];


GO
ALTER TABLE [dbo].[RPE_PARAMS] NOCHECK CONSTRAINT [FK_RPE_PARAMS_RPE_PARAM_NAMES];

