CREATE TABLE [dbo].[SER_PARAMS] (
    [SER_ID]     INT            NOT NULL,
    [PRM_ID]     INT            NOT NULL,
    [PRM_LONG]   INT            NULL,
    [PRM_STRING] NVARCHAR (255) NULL,
    [PRM_DOUBLE] FLOAT (53)     NULL,
    [PRM_DATE]   DATETIME       NULL,
    [PRM_CY]     MONEY          NULL,
    CONSTRAINT [PK_SER_PARAMS] PRIMARY KEY NONCLUSTERED ([SER_ID] ASC, [PRM_ID] ASC),
    CONSTRAINT [FK_SER_PARAMS_SER_PARAM_NAMES] FOREIGN KEY ([PRM_ID]) REFERENCES [dbo].[SER_PARAM_NAMES] ([PRM_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_SER_PARAMS_SERIES] FOREIGN KEY ([SER_ID]) REFERENCES [dbo].[SERIES] ([SER_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[SER_PARAMS] NOCHECK CONSTRAINT [FK_SER_PARAMS_SER_PARAM_NAMES];


GO
ALTER TABLE [dbo].[SER_PARAMS] NOCHECK CONSTRAINT [FK_SER_PARAMS_SERIES];


GO
GRANT DELETE
    ON OBJECT::[dbo].[SER_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[SER_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[SER_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[SER_PARAMS] TO [ap_public]
    AS [dbo];

