CREATE TABLE [dbo].[STATE_FLAGS] (
    [ST_ID]    INT           NOT NULL,
    [UID]      NVARCHAR (50) NOT NULL,
    [ST_FLAGS] INT           NULL,
    CONSTRAINT [PK_STATE_FLAGS2] PRIMARY KEY CLUSTERED ([ST_ID] ASC, [UID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_STATE_FLAGS_UID]
    ON [dbo].[STATE_FLAGS]([UID] ASC);

