CREATE TABLE [dbo].[STATE_WALK] (
    [SW_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [UID]     NVARCHAR (50) NOT NULL,
    [ST_FROM] INT           NOT NULL,
    [ST_TO]   INT           NOT NULL,
    CONSTRAINT [PK_STATE_WALK] PRIMARY KEY CLUSTERED ([SW_ID] ASC),
    CONSTRAINT [FK_STATE_WALK_STATES_FROM] FOREIGN KEY ([ST_FROM]) REFERENCES [dbo].[STATES] ([ST_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_STATE_WALK_STATES_TO] FOREIGN KEY ([ST_TO]) REFERENCES [dbo].[STATES] ([ST_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[STATE_WALK] NOCHECK CONSTRAINT [FK_STATE_WALK_STATES_FROM];


GO
ALTER TABLE [dbo].[STATE_WALK] NOCHECK CONSTRAINT [FK_STATE_WALK_STATES_TO];


GO
CREATE NONCLUSTERED INDEX [IX_STATE_WALK_ST_FROM]
    ON [dbo].[STATE_WALK]([ST_FROM] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_STATE_WALK_ST_TO]
    ON [dbo].[STATE_WALK]([ST_TO] ASC);

