CREATE TABLE [dbo].[SYS_PARAMS] (
    [PRM_NAME] NVARCHAR (50)  NOT NULL,
    [PRM_STR]  NVARCHAR (255) NULL,
    [PRM_LONG] INT            NULL,
    [PRM_DATE] DATETIME       NULL,
    CONSTRAINT [PK_SYS_PARAMS] PRIMARY KEY NONCLUSTERED ([PRM_NAME] ASC)
);

