CREATE TABLE [dbo].[TML_LINKS] (
    [PK]           INT IDENTITY (1, 1) NOT NULL,
    [TML_ID_LEFT]  INT NULL,
    [TML_ID_RIGHT] INT NULL,
    CONSTRAINT [PK_TML_LINKS] PRIMARY KEY CLUSTERED ([PK] ASC),
    CONSTRAINT [FK_TML_LINKS_TEMPLATES] FOREIGN KEY ([TML_ID_LEFT]) REFERENCES [dbo].[TEMPLATES] ([TML_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_TML_LINKS_TEMPLATES1] FOREIGN KEY ([TML_ID_RIGHT]) REFERENCES [dbo].[TEMPLATES] ([TML_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[TML_LINKS] NOCHECK CONSTRAINT [FK_TML_LINKS_TEMPLATES];


GO
ALTER TABLE [dbo].[TML_LINKS] NOCHECK CONSTRAINT [FK_TML_LINKS_TEMPLATES1];


GO
CREATE NONCLUSTERED INDEX [IX_TML_LINKS_LEFT]
    ON [dbo].[TML_LINKS]([TML_ID_LEFT] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_TML_LINKS_RIGHT]
    ON [dbo].[TML_LINKS]([TML_ID_RIGHT] ASC);

