CREATE TABLE [dbo].[TML_PARAMS] (
    [TML_ID]     INT            NOT NULL,
    [PRM_ID]     INT            NOT NULL,
    [PRM_LONG]   INT            NULL,
    [PRM_STRING] NVARCHAR (255) NULL,
    [PRM_DOUBLE] FLOAT (53)     NULL,
    [PRM_DATE]   DATETIME       NULL,
    [PRM_CY]     MONEY          NULL,
    CONSTRAINT [PK_TML_PARAMS] PRIMARY KEY NONCLUSTERED ([TML_ID] ASC, [PRM_ID] ASC),
    CONSTRAINT [FK_TML_PARAMS_TEMPLATES] FOREIGN KEY ([TML_ID]) REFERENCES [dbo].[TEMPLATES] ([TML_ID]) NOT FOR REPLICATION,
    CONSTRAINT [FK_TML_PARAMS_TML_PARAM_NAMES] FOREIGN KEY ([PRM_ID]) REFERENCES [dbo].[TML_PARAM_NAMES] ([PRM_ID]) NOT FOR REPLICATION
);


GO
ALTER TABLE [dbo].[TML_PARAMS] NOCHECK CONSTRAINT [FK_TML_PARAMS_TEMPLATES];


GO
ALTER TABLE [dbo].[TML_PARAMS] NOCHECK CONSTRAINT [FK_TML_PARAMS_TML_PARAM_NAMES];


GO
GRANT DELETE
    ON OBJECT::[dbo].[TML_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[TML_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[TML_PARAMS] TO [ap_public]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[TML_PARAMS] TO [ap_public]
    AS [dbo];

