CREATE TABLE [dbo].[USR_PARAMS] (
    [PRM_NAME]   NVARCHAR (50)  NOT NULL,
    [PRM_TYPE]   SMALLINT       NOT NULL,
    [PRM_STRING] NVARCHAR (255) NULL,
    [PRM_CY]     MONEY          NULL,
    [PRM_LONG]   INT            NULL,
    [PRM_DATE]   DATETIME       NULL,
    CONSTRAINT [PK_USR_PARAMS] PRIMARY KEY CLUSTERED ([PRM_NAME] ASC)
);

