----------------------------------------
create procedure ap_doclist_load7
@p1 int,
@p2 int,
@p3 int,
@p4 int,
@p5 int,
@p6 int,
@p7 int
as

set nocount on

select distinct DOCUMENTS.DOC_ID, DOCUMENTS.DOC_DONE,DOCUMENTS.DOC_DATE,
  DOCUMENTS.DOC_NAME, DOCUMENTS.DOC_MEMO, DOCUMENTS.DOC_NO,
  DOCUMENTS.FRM_ID, DOCUMENTS.DOC_SUM,DOCUMENTS.ST_ID,
  DOCUMENTS.DOC_TAG, DOCUMENTS.DOC_LINK, DOCUMENTS.TML_ID, 
  DOCUMENTS.DOC_PS1, DOCUMENTS.DOC_PS2, DOCUMENTS.DOC_PS3, 
  DOCUMENTS.DOC_PL1, DOCUMENTS.DOC_PL2, DOCUMENTS.DOC_PL3, 
  DOCUMENTS.DOC_PD1, DOCUMENTS.DOC_PD2, DOCUMENTS.DOC_PD3, 
  DOCUMENTS.DOC_PC1, DOCUMENTS.DOC_PC2, DOCUMENTS.DOC_PC3, 
  case when exists(SELECT * FROM BIND_DOCS AS T WHERE DOCUMENTS.DOC_ID=T.DOC_ID) then 1 else 0 end,
  DOCUMENTS.FLD_ID, DOCUMENTS.DOC_XSTATUS  
from DOCUMENTS
where DOC_ID=@p1 or DOC_ID=@p2 or DOC_ID=@p3 or DOC_ID=@p4 or 
      DOC_ID=@p5 or DOC_ID=@p6 or DOC_ID=@p7

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[ap_doclist_load7] TO [ap_public]
    AS [dbo];

